name: teracrafts_flagkit
description: Official Dart/Flutter SDK for FlagKit feature flag management
version: 1.0.5
repository: https://github.com/teracrafts/flagkit-sdk-dart
homepage: https://flagkit.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  meta: ^1.9.0
  crypto: ^3.0.3
  encrypt: ^5.0.3
  pointycastle: ^3.9.1

dev_dependencies:
  test: ^1.24.0
  mockito: ^5.4.0
  build_runner: ^2.4.0
